### ISSUE TITLE
Bug: a name that is being bound cannot use itself, even if it’s declared in enclosing scopes.

### ISSUE THREAD

**Issue by tristanlatr** [serge-sans-paille/beniget#44]
This name error is uncaught by `beniget`.

```python3
def outer():
    x = 1
    def middle():
        x = 1
        class mytype(str):
            x = x+1 # <- this triggers NameError: name 'x' is not defined
    return middle
outer()()
```

**Comment by serge-sans-paille** [comment]
wow, what an interesting setup. So what happens here (from a python point of view) is that within class scope, we cannot reference local variable from enclosing scope... probably because it would be ambigous? I get the same issue with

```
>>> def foo():
...   x = 1
...   class i:
...     x = x + 1
...   return i()
... 
>>> foo()
```

Any chance you would have any official ref on that behavior. @vstinner, any idea?

**Comment by serge-sans-paille** [comment]
https://docs.python.org/3/reference/executionmodel.html#resolution-of-names  gives an explanation, I'll try to implement that behavior correctly in beniget!

**Comment by vstinner** [comment]
> Any chance you would have any official ref on that behavior. @vstinner, any idea?

No idea.
